### ISSUE TITLE
Chinese garbage issue

### ISSUE THREAD

**Issue by pengfu** [spring-projects/spring-petclinic#141]
When I switch to use MYSQL database, I come across Chinese garbage issue. It seems that the issue occurs when writing database.I tried to change the sql to `CREATE DATABASE petclinic DEFAULT CHARACTER SET utf8;`,however it still doesn't work. It puzzled me and I have no idea right now.

**Comment by liouxiao** [comment]
Could you please show your `data-access.properties` file? I have no such issue, Chinese characters are displayed properly.

I suggest you'd check the properties file, especially in the MySQL jdbc url, do not forget to add `?useUnicode=true&characterEncoding=UTF-8` at the end, for example, the jdbc url might be:

```
jdbc.url=jdbc:mysql://localhost:3306/petclinic?useUnicode=true&characterEncoding=UTF-8
```

BTW, here's a forked `petclinic` project with Chinese i18n support.

**Comment by arey** [comment]
@pengfu, in order to support Chinise, the MySQL petclinic database should be created witch the following DDL statements:
```
ALTER DATABASE petclinic
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
```
and, like @liouxiao suggests, the JDBC URL should  be end with ```useUnicode=true&characterEncoding=UTF-8```

![petclinic-chinese](https://cloud.githubusercontent.com/assets/838318/14296493/b7ab80b4-fb7a-11e5-8315-8966f42d95b2.jpg)

**Comment by pengfu** [comment]
Thanks you guys,you have solved this problem perfectly! @liouxiao @arey
