### ISSUE TITLE
CSS missing

### ISSUE THREAD

**Issue by TheBaffledOne** [spring-projects/spring-petclinic#232]
The styling of the application seems to be missing. the file: /resources/css/petclinic.css" seems to be missing.

I assume this has something to do with less support not working. I am using latest code, EClipse Neon Neon.2 Release (4.6.2) and STS suite.

**Comment by arey** [comment]
The petclinic.css is generated by the wro4j-maven-plugin during the Maven build. Maybe an issue with Maven support in Eclipse?

**Comment by nsimonin1** [comment]
Before start application, you may run wro4j maven goal first `mvn wro4j:run`

**Comment by cotjoey** [comment]
I ran into the same issue in SpringSTS. 

The order I did things to get the issue were:
1. Download & extract the spring-petclinic-master.zip github project;
2. Import the project as a Maven project in SpringSTS;
3. When all the loading (building, etc) is complete, I delete the project (not from disk);
4. I import the project as a "General > Existing Projects into Workspace" and select "copy projects into workspace";
5. I modify the application-mysql.properties and launch the application once;
6. That when I get a 404 in the browser for "petclinic.css"

Solution:
1. Right-click the spring-petclinic project, click "Maven" then "Update Project...";
2. Relaunch the application
3. Your application now has the petclinic.css styles applied!

**Comment by dazlious** [comment]
cotjoey's last solution did it for me.

**Comment by ksarsecha** [comment]
If you are using IntelliJ IDEA, 
Right click the project -> click maven -> Generate Sources and Update Folders

**Comment by elab** [comment]
It's important to have m2e connector for wro4j-maven-plugin installed in Eclipse. 
Otherwise the m2e "Update project" will actually delete the petclinic.css file generated by normal Maven build!

Another important point is that the petclinic.css file gets not generated under `target/generated-resources` or `target/generated-sources` as one might expect, but under `target/classes`. That is pretty contra-intuitive. Even more, this folder is hidden in Eclipse so that a search for petclinic.css resource inside Eclipse (`Ctrl+Shift+R`) doesn't find anything.
