### ISSUE TITLE
the webjars issue, couldn't find jquery js

### ISSUE THREAD

**Issue by wanghongbin99** [spring-projects/spring-petclinic#441]
So strange, the following three links, the first two does not work, and return home directly, so the UI couldn't find css.

<script src="/webjars/jquery/2.2.4/jquery.min.js"></script>
<script src="/webjars/jquery-ui/1.11.4/jquery-ui.min.js"></script>
<script src="/webjars/bootstrap/3.3.6/js/bootstrap.min.js"></script>

**Comment by snicoll** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the guidelines for contributing](https://github.com/spring-projects/spring-boot/blob/master/CONTRIBUTING.adoc#using-github-issues), we prefer to use GitHub issues only for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.
