### ISSUE TITLE
Error after  ./mvnw spring-boot:run

### ISSUE THREAD

**Issue by Roytwsx3** [spring-projects/spring-petclinic#674]
After  ./mvnw spring-boot:run 
Receives this error. help

<img width="1736" alt="Screenshot 2020-09-15 at 4 11 21 PM" src="https://user-images.githubusercontent.com/20752887/93183864-1c363800-f76e-11ea-93cf-ddd3e14f2e11.png">

**Comment by ErnstHaagsman** [comment]
Did you by any chance download the repo as a ZIP rather than clone the Git repo? 

The message says it's looking for the Git history, so you'll need to clone the repository. See the ['Cloning an Exisiting Repository' section in the Git documentation](https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository).

**Comment by ebiggerr** [comment]
do you used "useNativeGit=true" in the configuration of the plugin?
if true, you have to need the native executable git binary that needs to be installed on your computer when using this option.
changing to **useNativeGit=false** might solve the issue, or install executable git in your computer in order to use the "useNativeGit-true" option.

**Comment by snicoll** [comment]
the project generates some git information that's show in `/actuator/info`. Please checkout this projet rather than downloading a detached state.
