### ISSUE TITLE
Feature/Websocket

### ISSUE THREAD

**Issue by pedsf1968** [spring-projects/spring-petclinic#699]
Add WebSocket to send informations messages to the user.

**Comment by pedsf1968** [comment]
ISSUE #699 I'm starting to work on it

**Comment by dsyer** [comment]
I'd be more than happy to see the websocket demo in your fork, or in the spring-petclinic organization maybe, if it's really useful. I'm not sure this is a good idea to put new features in the canonical Spring Petclinic (this one). We try to limit the scope so that it is realistic but not overwhelming for new users.
