### ISSUE TITLE
Failure during run: failed to lazily initialize a collection of role: org.springframework.samples.petclinic.owner.Pet.visits, could not initialize proxy - no Session

### ISSUE THREAD

**Issue by lonmiller** [spring-projects/spring-petclinic#901]
Deploying project as-is, when I ran as jar the owner lookups failed wtih error

`failed to lazily initialize a collection of role: org.springframework.samples.petclinic.owner.Pet.visits, could not initialize proxy - no Session
`
I did some searching and found the recommendation from 

 https://www.netsurfingzone.com/hibernate/failed-to-lazily-initialize-a-collection-of-role-could-not-initialize-proxy-no-session/

to add the following to application.properties:

`enable_lazy_load_no_trans=true`

but this setting was not recognized by Spring Boot so I did some more research and found:

https://www.baeldung.com/hibernate-lazy-loading-workaround

which specified the value as:

`spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true
`

This value resolved the error. I don't know if the setting is a valid fix or there's a structural component that needs to change so just documenting as an issue.

**Comment by dsyer** [comment]
Oops. We failed to test that after the model simplifications last week. I don't like taht config change much because it is global but we can simply make the visits eager instead. Fixed in bdcaa85. An alternative approach (which is still in the git history if anyone wants to look) is to traverse the lazy collection in the controller to force it to load.
