### ISSUE TITLE
Add deployment for spring boot in k8s

### ISSUE THREAD

**Issue by shivampateriya1** [spring-projects/spring-petclinic#968]
I want to contribute in the spring-pet clinic by adding k8s deployment file and SQL file in k8s.

**Comment by dsyer** [comment]
We've talked about it before but never really had a consensus on what should go into the manifest. There are lots of choices and not many are obviously right.

**Comment by xerx593** [comment]
> I want to contribute in the spring-pet clinic by adding k8s deployment file and SQL file in k8s.

I just want to mention: https://github.com/spring-petclinic/spring-petclinic-cloud (official fork)

**Comment by dsyer** [comment]
That would be a useful reference for anyone wanting to contribute. Also see here for some working example code: https://github.com/dsyer/spring-petclinic/tree/k8s.

I would say we need as few lines of YAML as we can get away with using just vanilla `kubectl` and Spring Boot features.

0) Use the image generated by `mvn spring-boot:build-image` and deploy either in a local repository or a public one (like dockerhub)
1) minimal service and deployment
2) just one database (probably mysql) and a config map following the [Service Binding](https://github.com/servicebinding/spec) spec because Spring Boot will pick that up automatically
3) maybe `/livez` and `/readyz` (can be exposed through a system property or application property)

**Comment by panic08** [comment]
> That would be a useful reference for anyone wanting to contribute. Also see here for some working example code: https://github.com/dsyer/spring-petclinic/tree/k8s.
> 
> I would say we need as few lines of YAML as we can get away with using just vanilla `kubectl` and Spring Boot features.
> 
> 0. Use the image generated by `mvn spring-boot:build-image` and deploy either in a local repository or a public one (like dockerhub)
> 1. minimal service and deployment
> 2. just one database (probably mysql) and a config map following the [Service Binding](https://github.com/servicebinding/spec) spec because Spring Boot will pick that up automatically
> 3. maybe `/livez` and `/readyz` (can be exposed through a system property or application property)

Didn't you implement this functionality in [your](https://github.com/dsyer/spring-petclinic/tree/k8s) fork?

**Comment by dsyer** [comment]
Yes I did. But I don’t maintain it, and no-one ever gave any feedback.

**Comment by dsyer** [comment]
Merged #1707
